# Material-use comparison only; NOT a printer or production profile.
# SPDX-License-Identifier: CC0-1.0
# Geometry and settings matched between original and candidate.
bed_shape = 0x0,220x0,220x220,0x220
max_print_height = 250
nozzle_diameter = 0.4
filament_diameter = 1.75
filament_density = 1.24
extrusion_multiplier = 1
layer_height = 0.2
first_layer_height = 0.2
perimeters = 3
top_solid_layers = 4
bottom_solid_layers = 4
fill_density = 15%
fill_pattern = grid
extrusion_width = 0.45
first_layer_extrusion_width = 0.45
perimeter_extrusion_width = 0.45
external_perimeter_extrusion_width = 0.45
infill_extrusion_width = 0.45
solid_infill_extrusion_width = 0.45
top_infill_extrusion_width = 0.45
support_material_extrusion_width = 0.45
perimeter_generator = arachne
support_material = 1
support_material_auto = 1
support_material_buildplate_only = 1
support_material_style = organic
support_material_threshold = 45
support_material_contact_distance = 0.25
support_material_interface_layers = 3
skirts = 0
brim_width = 0
raft_layers = 0
use_relative_e_distances = 1
gcode_comments = 1
start_gcode =
end_gcode =
before_layer_gcode =
layer_gcode =
temperature = 215
first_layer_temperature = 220
bed_temperature = 60
first_layer_bed_temperature = 60
